dataset: "flwrlabs/celeba"
cache_dir: ./dataset
n_epochs: 100
img_size: 128
batch_size: 32
num_workers: 4
pin_memory: True
shuffle: True
test_set: False
checkpoint_dir: "./checkpoints"
sample_dir: "./outputs/samples"
input_channels: 3
latent_dim: 128
hidden_dims: [32, 64, 128, 256, 512]
learning_rate: 1e-3
beta: 0.0005